### ISSUE TITLE
Proper handling of `auto_now_add` and `auto_now`

### ISSUE THREAD

**Issue by bryanhoulton** [tfranzel/drf-spectacular#1063]
Trying to make a simple API with a model that has a field `auto_now_add`. 

Fields with `auto_now_add` set are marked as required when creating via a viewset. Am I misconfiguring anything? I'll attach my serializer, model, and view.

```py
class ReadReceipt(models.Model):
    zip = models.ForeignKey(Zip, on_delete=models.CASCADE)
    receiver = models.ForeignKey(Zipper, on_delete=models.CASCADE, blank=True)
    read_time = models.DateTimeField(auto_now=True, blank=True)
```

```py
class ReadReceiptSerializer(serializers.ModelSerializer):
    read_time = serializers.DateTimeField(read_only=True, required=False)

    class Meta:
        model = ReadReceipt
        fields = [
            "zip",
            "read_time",
        ]
```

```py
class ReadReceiptViewSet(ModelViewSet):
    queryset = ReadReceipt.objects.all()
    serializer_class = ReadReceiptSerializer
    permission_classes = [IsAuthenticated]
    authentication_classes = [TokenAuthentication]

    def get_queryset(self):
        return ReadReceipt.objects.filter(receiver=self.request.user)
```
Here's the output schema for this model.
```yml
ReadReceipt:
      type: object
      properties:
        zip:
          type: integer
        read_time:
          type: string
          format: date-time
          readOnly: true
      required:
      - read_time
      - zip
```
