### ISSUE TITLE
Polymorphism (oneOf) with pydantic union discriminator

### ISSUE THREAD

**Issue by Zerotask** [tfranzel/drf-spectacular#1081]
I have the following pydantic models:
```python
class EUTaxonomyValue(BaseModel):
    type: Literal["eu_taxonomy"] = "eu_taxonomy"
    nace_code: str
    economic_activity: str
    classification: str | None


class EconomicActivity(BaseModel):
    type: Literal["economic_activity"] = "economic_activity"
    activity_code: str
    activity_name: str


class DateRange(BaseModel):
    type: Literal["daterange"] = "daterange"
    start_date: date
    end_date: date

ComplexValue = Annotated[
    None | EUTaxonomyValue | EconomicActivity | DateRange,
    Field(discriminator="type", title="Complex Value"),
]
```

Now I define a new field `value_complex` in one of my serializers:
```python
class FieldValueSerializer(serializers.ModelSerializer):
    value_complex = SchemaField(schema=ComplexValue, required=False)
```

SchemaField is from https://pypi.org/project/django-pydantic-field/ therefore I'm not sure if this issue is related to spectacular or not.

The generated Open API 3 Schema is invalid.

<details>
  #/paths/~1api~1report-requests~1{id}~1details~1/get/responses/200/content/application~1json/schema/properties/report/allOf/0/properties/field_values/items/properties/value_complex must NOT have additional properties
  #/paths/~1api~1report-requests~1{id}~1details~1/get/responses/200/content/application~1json/schema/properties/report/allOf/0/properties/field_values/items/properties/value_complex must have required property '$ref'
  #/paths/~1api~1report-requests~1{id}~1details~1/get/responses/200/content/application~1json/schema/properties/report/allOf/0/properties/field_values/items/properties/value_complex must match exactly one schema in oneOf
  #/paths/~1api~1report-requests~1{id}~1details~1/get/responses/200/content/application~1json/schema/properties/report/allOf/0/properties/field_values/items must have required property '$ref'
  #/paths/~1api~1report-requests~1{id}~1details~1/get/responses/200/content/application~1json/schema/properties/report/allOf/0/properties/field_values/items must match exactly one schema in oneOf
  #/paths/~1api~1report-requests~1{id}~1details~1/get/responses/200/content/application~1json/schema/properties/report/allOf/0/properties/field_values must have required property '$ref'
  #/paths/~1api~1report-requests~1{id}~1details~1/get/responses/200/content/application~1json/schema/properties/report/allOf/0/properties/field_values must match exactly one schema in oneOf
  #/paths/~1api~1report-requests~1{id}~1details~1/get/responses/200/content/application~1json/schema/properties/report/allOf/0 must have required property '$ref'
  #/paths/~1api~1report-requests~1{id}~1details~1/get/responses/200/content/application~1json/schema/properties/report/allOf/0 must match exactly one schema in oneOf
  #/paths/~1api~1report-requests~1{id}~1details~1/get/responses/200/content/application~1json/schema/properties/report must have required property '$ref'
  #/paths/~1api~1report-requests~1{id}~1details~1/get/responses/200/content/application~1json/schema/properties/report must match exactly one schema in oneOf
  #/paths/~1api~1report-requests~1{id}~1details~1/get/responses/200/content/application~1json/schema must have required property '$ref'
  #/paths/~1api~1report-requests~1{id}~1details~1/get/responses/200/content/application~1json/schema must match exactly one schema in oneOf
  #/paths/~1api~1report-requests~1{id}~1details~1/get/responses/200 must have required property '$ref'
  #/paths/~1api~1report-requests~1{id}~1details~1/get/responses/200 must match exactly one schema in oneOf
  #/paths/~1api~1report~1field-values~1/get/responses/200/content/application~1json/schema/properties/results/items/properties/value_complex must NOT have additional properties
  #/paths/~1api~1report~1field-values~1/get/responses/200/content/application~1json/schema/properties/results/items/properties/value_complex must have required property '$ref'
  #/paths/~1api~1report~1field-values~1/get/responses/200/content/application~1json/schema/properties/results/items/properties/value_complex must match exactly one schema in oneOf
  #/paths/~1api~1report~1field-values~1/get/responses/200/content/application~1json/schema/properties/results/items must have required property '$ref'
  #/paths/~1api~1report~1field-values~1/get/responses/200/content/application~1json/schema/properties/results/items must match exactly one schema in oneOf
  #/paths/~1api~1report~1field-values~1/get/responses/200/content/application~1json/schema/properties/results must have required property '$ref'
  #/paths/~1api~1report~1field-values~1/get/responses/200/content/application~1json/schema/properties/results must match exactly one schema in oneOf
  #/paths/~1api~1report~1field-values~1/get/responses/200/content/application~1json/schema must have required property '$ref'
  #/paths/~1api~1report~1field-values~1/get/responses/200/content/application~1json/schema must match exactly one schema in oneOf
  #/paths/~1api~1report~1field-values~1/get/responses/200 must have required property '$ref'
  #/paths/~1api~1report~1field-values~1/get/responses/200 must match exactly one schema in oneOf
</details>

```yaml
value_complex:
          title: value_complex
          discriminator:
            propertyName: type
            mapping:
              eu_taxonomy: '#/definitions/EUTaxonomyValue'
              economic_activity: '#/definitions/EconomicActivity'
              daterange: '#/definitions/DateRange'
          oneOf:
          - title: EUTaxonomyValue
            type: object
            properties:
              type:
                title: Type
                default: eu_taxonomy
                enum:
                - eu_taxonomy
                type: string
              nace_code:
                title: Nace Code
                type: string
              economic_activity:
                title: Economic Activity
                type: string
              classification:
                title: Classification
                type: string
            required:
            - nace_code
            - economic_activity
          - title: EconomicActivity
            type: object
            properties:
              type:
                title: Type
                default: economic_activity
                enum:
                - economic_activity
                type: string
              activity_code:
                title: Activity Code
                type: string
              activity_name:
                title: Activity Name
                type: string
            required:
            - activity_code
            - activity_name
          - title: DateRange
            type: object
            properties:
              type:
                title: Type
                default: daterange
                enum:
                - daterange
                type: string
              start_date:
                title: Start Date
                type: string
                format: date
              end_date:
                title: End Date
                type: string
                format: date
            required:
            - start_date
            - end_date
          definitions:
            EUTaxonomyValue:
              title: EUTaxonomyValue
              type: object
              properties:
                type:
                  title: Type
                  default: eu_taxonomy
                  enum:
                  - eu_taxonomy
                  type: string
                nace_code:
                  title: Nace Code
                  type: string
                economic_activity:
                  title: Economic Activity
                  type: string
                classification:
                  title: Classification
                  type: string
              required:
              - nace_code
              - economic_activity
            EconomicActivity:
              title: EconomicActivity
              type: object
              properties:
                type:
                  title: Type
                  default: economic_activity
                  enum:
                  - economic_activity
                  type: string
                activity_code:
                  title: Activity Code
                  type: string
                activity_name:
                  title: Activity Name
                  type: string
              required:
              - activity_code
              - activity_name
            DateRange:
              title: DateRange
              type: object
              properties:
                type:
                  title: Type
                  default: daterange
                  enum:
                  - daterange
                  type: string
                start_date:
                  title: Start Date
                  type: string
                  format: date
                end_date:
                  title: End Date
                  type: string
                  format: date
              required:
              - start_date
              - end_date
```

Regarding https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/ `oneOf` should have a list of `$ref` and those 3 pydantic models should be defined in `#/components/schemas/`
