### ISSUE TITLE
How to only include `ApiKeyAuth` authentication/authorization strategy?

### ISSUE THREAD

**Issue by alexburner** [tfranzel/drf-spectacular#1094]
### Describe the bug

We are only exposing endpoints that use `djangorestframework-api-key` in our generated schemas. We're following the blueprint instructions [here](https://github.com/tfranzel/drf-spectacular/blob/0.25.1/docs/blueprints.rst#djangorestframework-api-key) to include `ApiKeyAuth`.

However, we're also seeing `basicAuth` and `cookieAuth` in the generated docs, how do we suppress those?

Including an empty list for `AUTHENTICATION_WHITELIST` does not seem to affect it.

### To Reproduce

In `settings.py`:
```py
SPECTACULAR_SETTINGS = {
    # ...
    "AUTHENTICATION_WHITELIST": [],
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "ApiKeyAuth": {
                "type": "apiKey",
                "in": "header",
                "name": "Authorization",
            }
        }
    },
    "SECURITY": [{"ApiKeyAuth": []}],
}
```

### Expected behavior
We would like to only see the `ApiKeyAuth` strategy in generated docs

### Observed behavior
We also see `basicAuth` and `cookieAuth`

In Swagger "Authorize":
![Screenshot 2023-10-31 at 8 49 45 AM](https://github.com/tfranzel/drf-spectacular/assets/409114/c4250f74-b535-42c9-bceb-14a49eb31f09)

In Redoc "Authorizations":
![Screenshot 2023-10-31 at 8 57 33 AM](https://github.com/tfranzel/drf-spectacular/assets/409114/247291d5-0a93-40ed-bf80-96c5143f1d51)

In `.yaml` file "securitySchemes":
```yml
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
```
