### ISSUE TITLE
Parameter that is required, but optional on the ModelField is has the "null" type included

### ISSUE THREAD

**Issue by gabn88** [tfranzel/drf-spectacular#1211]
**Describe the bug**
A model with a public_access_uuid (UUIDField(blank=True,null=True)) is used as a path paramater, let's say:

```
/api/order/{public_access_uuid}
```
This results in a scheme:

```
      parameters:
        - in: path
          name: public_access_uuid
          schema:
            type:
              - string
              - 'null'
            format: uuid
          required: true
```

As you can see the 'null' and required: true do bite eachother. And because of this scheme, the swagger-ui cannot be used for this endpoint and gives `Required field is not provided`.

**To Reproduce**
Add a ModelField like about.
Add a ModelSerializer with that field as lookup_field.

**Expected behavior**
The null type can be omitted.

I tried to explicitly add a public_access_uuid = serializers.UUIDField, with different options (required=True, allow_null=False), but that did not help.

I have now overridden it with:
```
    parameters=[
        OpenApiParameter(
            "public_access_uuid", OpenApiTypes.UUID, OpenApiParameter.PATH
        ),  # path variable was overridden
    ],
```
And that works, but it would be nice to have it work out of the box.
