### ISSUE TITLE
Invalid openAPI emitted when nullable and no top level type

### ISSUE THREAD

**Issue by jayvdb** [tfranzel/drf-spectacular#130]
If a schema has no top level `type`, such as when it is instead using `oneOf`, `anyOf`, etc, injecting `nullable: true` is invalid.

https://spec.openapis.org/oas/v3.0.3#fixed-fields-19

> (nullable) A true value adds "null" to the allowed type specified by the type keyword, only if type is explicitly defined within the same Schema Object.

I guess this requires special handling that groks oneOf, anyOf, etc and adds another schema to those lists with `type: null`.

**Comment by jayvdb** [comment]
Some useful analysis of existing implementations at https://github.com/pglass/py-openapi-schema-to-json-schema/issues/10 .

tl;dr: some tools are accepting `nullable: true` even if `type: ..` is not present, and trying to make sense of it.

But it would be safer to not cause this schema, or have a postprocessor that detects and adjusts the schema to something more sensible.

In order to not cause this schema, the `OpenApiSerializerFieldExtension` probably needs some enhancement so that it handles `null=True` (and others?), and the core drf-spectacular doesnt add `nullable: true` to the schema.

**Comment by tfranzel** [comment]
i see. makes sense. @jayvdb not quite sure how to provoke that situation though. is this still happening and if so could you describe the situation under which this happens?

**Comment by jayvdb** [comment]
https://github.com/tfranzel/drf-spectacular/pull/38 is an example where it happens.  One of the many reasons it is blocked.

**Comment by tfranzel** [comment]
@jayvdb i have a hard time figuring this out without a proper example. this is what spectacular generates with #38 and current master merged into. this needs to be unpacked.

1. core spectacular does indeed add `nullable: true` where appropriate. maybe not at the time of the PR but now it does.
2.  i don't see a deficiency with `OpenApiSerializerFieldExtension`
3. with your statement itself i do a agree
    > If a schema has no top level type, such as when it is instead using oneOf, anyOf, etc, injecting nullable: true is invalid.

   however, i don't see it happening here. the serializer component `X` is the top level here and it does have a type. `nullable` would only take effect on its properties, where it is ok.


```yaml
components:
  schemas:
    X:
      type: object
      properties:
        location:
          # nullable: true  # ALSO VALIDATES WITH THIS
          oneOf:
          - type: object
            properties:
              type:
                description: The type of the geos instance
                type: string
                enum:
                - Point
                - LineString
                - LinearRing
                - Polygon
                - MultiPoint
                - MultiLineString
                - MultiPolygon
              coordinates:
                # nullable: true  # ALSO VALIDATES WITH THIS
                oneOf:
                - type: array
                  items:
                    type: number
                    format: float
                - type: array
                  items:
                    type: array
                    items:
                      type: number
                      format: float
                - type: array
                  items:
                    type: array
                    items:
                      type: array
                      items:
                        type: number
                        format: float
                - type: array
                  items:
                    type: array
                    items:
                      type: array
                      items:
                        type: array
                        items:
                          type: number
                          format: float
```
