### ISSUE TITLE
[django-filters] extend_schema_field forgets help_text

### ISSUE THREAD

**Issue by bart-maykin** [tfranzel/drf-spectacular#1323]
**Describe the bug**

When using extend_schema_field in conjunction with a django-filters filter class, the help_text when overwriting the filter as a field dissapears in the schema generation.

**To Reproduce**

```python 
extend_schema_field(UUID)
class BadExamplefilter(filters.CharFilter):
    ...
```

```python
class SomeFilterSetClass(FilterSet):
    test = BadExamplefilter(
        help_text="a very important help text",
        ...
    )
    
    class Meta:
        model = Foo
        fields = ("test",)
```

**Expected behavior**

Expected behavior:
```yaml
- in: query
  name: test
  schema:
    type: string
    format: uuid
  description: a very important help text
```

Current behavior:
```yaml
- in: query
  name: test
  schema:
    type: string
    format: uuid
```

**Versions**

- python: 3.12
- django: 4.2
- drf spectacular: 0.27.2
- django-filters: 24.3
