### ISSUE TITLE
JSONField is not processing correctly

### ISSUE THREAD

**Issue by DanilaCharushin** [tfranzel/drf-spectacular#1340]
**Describe the bug**

`Django: 5.1.3`
`djangorestframework: 3.15.2`
`drf-spectacular: 0.28.0`

When using `models.JSONField(...)`, DRF correctly generates `serializers.JSONField(...)`. However, drf-spectacular has a special condition for handling this field (see `drf_spectacular/openapi.py:607`), which seems to be the reason I'm getting empty fields in the OpenAPI schema, such as `{}` instead of the expected object representation.

**To Reproduce**

```python
# models.py
from django.db import models

class TurboModel(models.Model):
    ultra_json_field = models.JSONField()


# serializers.py
from rest_framework import serializers

class TurboModelSerializer(serializers.ModelSerializer):
    class Meta:
        model = TurboModel
        fields = "__all__"
```

The DRF representation of `TurboModelSerializer` is as follows:
```python
TurboModelSerializer():
    id = IntegerField(label='ID', read_only=True)
    ultra_json_field = JSONField(decoder=None, encoder=None, style={'base_template': 'textarea.html'})
```

In SwaggerUI, the schema for the `field ultra_json_field` appears empty:
<img width="300" alt="image" src="https://github.com/user-attachments/assets/4fc890c3-6873-489c-8f7b-f4eb53c11fd6">

The YAML version of the OpenAPI schema looks like this:

```yaml
components:
  schemas:
    TurboModel:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        ultra_json_field: { }
      required:
        - id
        - ultra_json_field
```

**Expected behavior**

The expected YAML OpenAPI schema should be:
```yaml
    TurboModel:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        ultra_json_field:
          type: object
          additionalProperties: {}
      required:
      - id
      - ultra_json_field
```

This can be achieved by adding a `SerializerMethodField` and setting the correct type hint, as shown below:
```python
class TurboModelSerializer(serializers.ModelSerializer):
    ultra_json_field = serializers.SerializerMethodField()

    @staticmethod
    def get_ultra_json_field(obj: TurboModel) -> dict:
        return obj.ultra_json_field

    class Meta:
        model = TurboModel
        fields = "__all__"
```

However, it would be ideal if drf-spectacular could handle this automatically.

**P.S.**
Thank you for your work - I'm really enjoying this package! If I'm mistaken about this issue or if there's a better way to address it, please let me know.

Best regards!
