### ISSUE TITLE
Non-unique operationId

### ISSUE THREAD

**Issue by jayvdb** [tfranzel/drf-spectacular#137]
> operationId | string | Unique string used to identify the operation. The id MUST be unique  among all operations described in the API. The operationId value is case-sensitive.  Tools and libraries MAY use the operationId to uniquely identify an  operation, therefore, it is RECOMMENDED to follow common programming  naming conventions.

```yaml
  /oscarapi/checkout/payment-states/:
    get:
      operationId: oscarapi_checkout_payment_states_retrieve
      ...
  /oscarapi/checkout/payment-states/{id}/:
    get:
      operationId: oscarapi_checkout_payment_states_retrieve
      ...
```
