### ISSUE TITLE
Camel case does not adjust path parameters

### ISSUE THREAD

**Issue by jayvdb** [tfranzel/drf-spectacular#138]
While path param names are internal to the spec doc, effectively only placeholders, having no bearing on actual use of the API, it is odd to use djangorestframework-camel-case and have snake case used for these path parameters while the rest of the spec uses camel case.

```yaml
  /oscarapi/baskets/{basket_pk}/lines/{id}/:
    get:
      operationId: oscarapi_baskets_lines_retrieve
      description: |-
        Only the field `quantity` can be changed in this view.
        All other fields are readonly.
      parameters:
      - in: path
        name: basket_pk
        schema:
          type: integer
        required: true
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Cart line.
        required: true
```
