### ISSUE TITLE
Support DictField with child

### ISSUE THREAD

**Issue by zach-waggoner** [tfranzel/drf-spectacular#142]
There doesn't seem to be any way to represent dictionaries with a known value type. For example, this:

```py
class ExampleSerializer(serializers.Serializer):
    dictionary = serializers.DictField(child=serializers.IntegerField())
```

produces this:

```yaml
Example:
  type: object
  properties:
    dictionary:
      type: object
      additionalProperties: {}
```

It would be nice if it would instead produce this:

```yaml
Example:
  type: object
  properties:
    dictionary:
      type: object
      additionalProperties:
        type: integer
```
