### ISSUE TITLE
Model schemas for create methods mark pk fields as required

### ISSUE THREAD

**Issue by bharling** [tfranzel/drf-spectacular#197]
**Describe the bug**
Sorry to keep posting issues .... 🤦, again this may be specific to the python client generator as part of openapi-generator but with the schema generated by spectacular, for models used in create methods it seems to mark the pk field as both read-only _and_ required, which means you cannot use the model definitions in create methods. This can be worked around obviously but it seems like it would be good to resolve somehow

**To Reproduce**
Generate schema for any model in the app - example below:

```
    MeetingProposal:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        revisions:
          type: array
          items:
            type: integer
        title:
          type: string
          maxLength: 128
        cancelled:
          type: boolean
        created_by:
          type: integer
        selected_revision:
          type: integer
          nullable: true
      required:
      - created_by
      - id
```

**Expected behavior**
The example above shows the `id` field as both required _and_ read-only. When compiled into a python with client-side validation this means you cannot instantiate a model locally without filling the `id` field, so cannot use the model in `create` methods. It would be handy if the serializer -> schema functions could generate an alternative model for POST ops, that did not require the pk.
