### ISSUE TITLE
Request component properties not marked as required when using `COMPONENT_SPLIT_REQUEST=True`

### ISSUE THREAD

**Issue by rvinzent** [tfranzel/drf-spectacular#243]
**Describe the bug**
When setting the `COMPONENT_SPLIT_REQUEST` setting to `True`, the generated components do not indicate that any field is required.

**To Reproduce**
- `COMPONENT_SPLIT_REQUEST=True` in settings

This serializer produces the following components:
```python
class RequiredSerializer(serializers.Serializer):
    read_only_property = serializers.CharField(read_only=True, required=True)
    required_property = serializers.CharField(required=True)
```

```yaml
    Required:
      type: object
      properties:
        read_only_property:
          type: string
          readOnly: true
        required_property:
          type: string
      required:
      - read_only_property
      - required_property
    
    RequiredRequest:
      type: object
      properties:
        required_property:
          type: string
```

**Expected behavior**
In the above example `RequiredRequest` is missing the `required` properties list. It should generate
```yaml
    RequiredRequest:
      type: object
      properties:
        required_property:
          type: string
      required:
      - required_property
```
This is causing issues with client code generation tools.

**Comment by tfranzel** [comment]
```
>       assert not (read_only and required), NOT_READ_ONLY_REQUIRED
E       AssertionError: May not set both `read_only` and `required`

../venv/lib/python3.8/site-packages/rest_framework/fields.py:336: AssertionError
``` 

is invalid according to DRF and won't run. you cannot set `read_only=True` and `required=True` at the same time. Also its important to note that DRF's `read_only` semantics differ from the drf-spectacular/OpenApi semantics. spectacular will put them where it can automatically.

simply removing `read_only=True` will yield the following for me. Looks like your expected behavior as far as i can tell.

```yaml
    Required:
      type: object
      properties:
        read_only_property:
          type: string
          readOnly: true
        required_property:
          type: string
      required:
      - read_only_property
      - required_property
    RequiredRequest:
      type: object
      properties:
        required_property:
          type: string
      required:
      - required_property
```

**Comment by rvinzent** [comment]
Oops, yea you can't explicitly set `required=True`, but if I remove `read_only=True` the parameter will appear in the generated `_Request` component, which is not what I want. 

Not sure if it's possible to produce the correct spec without some overrides 😔

Thanks

**Comment by rvinzent** [comment]
@tfranzel I'm going to open an issue on DRF because frankly, a `read_only` field does _not_ imply the field is `required=False`. It turns out it's possible to optionally include `required=False` fields on the serialization path. DRF checks if the attribute exists when deciding to include it in the payload. I might want to indicate to DRF that the attribute must be present, even if the field is `read_only`.

**Comment by tfranzel** [comment]
> - required_property     # this is not included at the moment, even though it is a required field 

i cannot confirm this statement. for me this is actually included. 

i tried to compile all the cases here:

```python
    class XSerializer(serializers.Serializer):
        plain_property = serializers.CharField()

        required_property = serializers.CharField(required=True)
        non_required_property = serializers.CharField(required=False)

        read_only_property = serializers.CharField(read_only=True)
        read_only_non_required_property = serializers.CharField(read_only=True, required=False)

        write_only_property = serializers.CharField(write_only=True)
        write_only_non_required_property = serializers.CharField(write_only=True, required=False)
```

which yielded for me:

```yaml
    X:
      type: object
      properties:
        plain_property:
          type: string
        required_property:
          type: string
        non_required_property:
          type: string
        read_only_property:
          type: string
          readOnly: true
        read_only_non_required_property:
          type: string
          readOnly: true
      required:
      - plain_property
      - read_only_non_required_property
      - read_only_property
      - required_property
    XRequest:
      type: object
      properties:
        plain_property:
          type: string
        required_property:
          type: string
        non_required_property:
          type: string
        write_only_property:
          type: string
          writeOnly: true
        write_only_non_required_property:
          type: string
          writeOnly: true
      required:
      - plain_property
      - required_property
      - write_only_property
```

the `required_property` is included in both schema's required list, so its looks like as expected to me.

the only thing that bothers me here is `read_only_non_required_property` being in the response's required list, but i have not tested whether this is actually honored by DRF.
