### ISSUE TITLE
Style deepObject

### ISSUE THREAD

**Issue by igormaraujo** [tfranzel/drf-spectacular#309]
HI, i'm develop a API that has a filter at query parameter like this:

myapi.com?filter[last_name]=foo

I saw that the OpenAPI 3.0.0 has the deepObject style but I don't see at the drf-spetacular how to add a schema to OpenApiParameter. i would like to generate something like below as i saw at stackoverflow link https://stackoverflow.com/questions/63862351/openapi-how-to-describe-query-parameters

````
parameters:
  - in: query
    name: filter
    style: deepObject
    allowReserved: true
    schema:
      type: object
      properties:
        post:
          type: array
          items:
            type: string
        author:
          type: array
          items:
            type: string
````
