### ISSUE TITLE
DecimalField represented as type string with minimum and maximum

### ISSUE THREAD

**Issue by idesoto-rover** [tfranzel/drf-spectacular#335]
**Describe the bug**
`DecimalField` fields that use `max_digits` or `decimal_places` are represented in the schema as a type `string` with `minimum` and `maximum` properties, but according to the [specs](https://swagger.io/docs/specification/data-models/data-types/#numbers) (or what I understand of them) is that `minimum` and `maximum` properties only apply to fields of type `number`.

This is giving me issues in the validation library I'm using (drf-openapi-tester) because it expects that fields with `minimum` and `maximum` properties to be numbers. After checking the specs IMHO the problem is in the schema (even if the validation library could be a bit more flexible and not fail on this).

**To Reproduce**
E.g.: for this field:
```
    latitude = serializers.DecimalField(
        max_digits=7,
        decimal_places=3
    )
```
This is generated in the schema:
```
        latitude:
          type: string
          format: decimal
          maximum: 10000
          minimum: -10000
```

**Expected behavior**
Maybe instead of specifying minimum and maximum values, specify a string pattern? Something like `^\d{1,7}(?:\.\d{1,3})?$` if `max_digits` is 7 and `decimal_places` is 3.
```
        latitude:
          type: string
          format: decimal
          pattern: ^\d{1,7}(?:\.\d{1,3})$
```
