### ISSUE TITLE
Show Enum label in schema

### ISSUE THREAD

**Issue by krzysieqq** [tfranzel/drf-spectacular#337]
Hi,
Is there any easy way to show the enum label in the schema. I'm using Django 3+ which allow to declarate choices as enums with label as human-readable form (https://docs.djangoproject.com/en/3.1/ref/models/fields/#enumeration-types). I'd like to show label in schema and swagger UI for easier user choice. Is there any easy option to show this in swagger UI?

**Comment by tfranzel** [comment]
there is no concept for choice labels in OpenAPI. the only thing one could do is generating a description that contains all the choice label tuples. certainly an option.

**Comment by krzysieqq** [comment]
Ok, I see that there is issue for that in openApi https://github.com/OAI/OpenAPI-Specification/issues/681

**Comment by tfranzel** [comment]
ahh i see. thanks for the research. we could hack together a description string but i would prefer not to.  

regarding the solutions in OAI/OpenAPI-Specification#681: we should wait until some kind of extension/vocabulary support emerges in swagger UI or redoc. its easy for us to add this, but if there is no support we gain nothing at the moment.

**Comment by bahag-raesenerm** [comment]
Hey everybody,
trying my luck to hook here in. Is there any suggested solution yet? it seems from OpenAPI spec there is the following recommendation:
```yaml
codeGen: namedEnum
oneOf:
  - const: 1
    title: Sunny
    description: Blue sky
  - const: 2
    title: Cloudy
    description: Slightly overcast
  - const: 3
    title: Rainy
    description: Take an umbrella with you
```
see https://github.com/OAI/OpenAPI-Specification/issues/681#issuecomment-1084952860

any hints appreciated
