### ISSUE TITLE
Path patterns

### ISSUE THREAD

**Issue by samfrances** [tfranzel/drf-spectacular#356]
Is there a way to get drf-spectacular to pick up regex in url config so that it can specify a regex pattern in the path schema?

For example:

```
re_path(r'foo/(?P<sha256sum>[a-f0-9]{64})', my_view),
```
Should result in:

```
  /foo/{sha256sum}/:
    get:
      parameters:
      - in: path
        name: hashbin_ref
        schema:
          type: string
          pattern: "^[a-f0-9]{64}$"
        required: true
```
If this isn't currently possible, perhaps this would be a good feature?

In addition, I can't find any way to use `@extend_schema` to manually specify a pattern.
