### ISSUE TITLE
Python 3.6 & 3.7 differences on SerializerMethodField w/ complex type

### ISSUE THREAD

**Issue by pb-dod** [tfranzel/drf-spectacular#374]
**Describe the bug**

This might be somewhat related to #207, but I'm getting a different schema on python 3.6 vs 3.7.

I've got a `SerializerMethodField` that has a dict with a mildly complex type (with a `Union`):
```
    complex_field_method_object = serializers.SerializerMethodField()

    def get_complex_field_method_object(self, obj) -> Dict[str, Union[int, bool]]:
        if obj.pk:
            return {'test_int_bool': obj.pk}
        return {'test_int_bool': False}
```

On python 3.7, this will output the correct schema:
```
        complex_field_method_object:
          type: object
          additionalProperties:
            oneOf:
            - type: integer
            - type: boolean
          readOnly: true
```

On python 3.6, this will output an **incorrect** schema (detecting the field as an integer only):
```
        complex_field_method_object:
          type: object
          additionalProperties:
            type: integer
          readOnly: true
```

**To Reproduce**
I've created a test that fails on python 3.6 (but not 3.7): https://github.com/pb-dod/drf-spectacular/commit/dd686b860ae418a47fdca2520f3af38f0d49e6eb

I'm able to reproduce this issue on both drf-spectacular 0.14.0 and the most recent release (0.15.1).

**Expected behavior**
Both python 3.6 and 3.7 should detect the field as accepting both an integer and boolean:
```
oneOf:
- type: integer
- type: boolean
```
