### ISSUE TITLE
Non-editable, nullable (boolean) model field generates as required and not nullable

### ISSUE THREAD

**Issue by NANASHI0X74** [tfranzel/drf-spectacular#449]
**Describe the bug**
As title says.

**To Reproduce**
A model with a field like this:
```python
class User(AbstractUser):
    invite = models.BooleanField(editable=False, null=True)
```
will produce a schema component like this:
```yaml
    UserDetail:
      type: object
      properties:
        invite:
          type: boolean
          readOnly: true
      required:
      - invite
```

this is a problem in nullsafe code generators because this field will be a non-nullable property and if the property is null, deserializing it will throw an error.
  for reference, settings:
```
    'ENUM_ADD_EXPLICIT_BLANK_NULL_CHOICE': False,
    'COMPONENT_SPLIT_REQUEST': True,
```

**Expected behavior**
Either have a nullable boolean field (if openapi allows that) or not have the field be required.

**Workaround**
setting `'COMPONENT_NO_READ_ONLY_REQUIRED': True` will fix this, but isn't ideal, because id fields among others may then get generated as nullable
