### ISSUE TITLE
Boolean filter is not picked properly

### ISSUE THREAD

**Issue by francipvb** [tfranzel/drf-spectacular#562]
**Describe the bug**
The boolean filter's type is not picked properly.

**To Reproduce**
For example I have these two fields:

```python
    end = django_filters.IsoDateTimeFromToRangeFilter()
    is_indefinite = django_filters.BooleanFilter("end", "isnull")
```

And this variation of the second field:

```python
    is_indefinite = django_filters.BooleanFilter("end__isnull")
```

The first field is picked properly, including the type, but the second is picked as a string in the second variation and as a datetime in the first variation.

**Expected behavior**
Representation typed as _boolean_ parameter.

**Comment by tfranzel** [comment]
```python
    available_till = django_filters.IsoDateTimeFromToRangeFilter()
    is_indefinite = django_filters.BooleanFilter('available_till', 'isnull')
    is_indefinite2 = django_filters.BooleanFilter('available_till__isnull')
```
to me this looks exactly like it's supposed to be.

```yaml
        name: available_till_after
        schema:
          type: string
          format: date-time
      - in: query
        name: available_till_before
        schema:
          type: string
          format: date-time
           .....................
      - in: query
        name: is_indefinite
        schema:
          type: boolean
      - in: query
        name: is_indefinite2
        schema:
          type: boolean

```
