### ISSUE TITLE
django-filter BaseInFilter type customization

### ISSUE THREAD

**Issue by quertenmont** [tfranzel/drf-spectacular#599]
Hello,

I am using django-filter with a classical "CharInFilter" that is defined (as recommended) by

```
class CharInFilter(BaseInFilter, CharFilter):
    pass
```
The open api type that comes out of this is 'array[string]', but that's incorrect, as the input is actually comma separated values the right type should be 'string'.
I tried to customize this class in order to fix the issue via:

```
from drf_spectacular.contrib.django_filters import DjangoFilterExtension
class CharInFilterExtension(DjangoFilterExtension):
    target_class = CharInFilter
    priority = 1
    match_subclasses = True

    def map_serializer_field(self, auto_schema, direction):
        return build_basic_type(OpenApiTypes.STR)

```
but this doesn't seem to have any effect.
I would appreciate recommendation on how to customize this.

Thanks for helping,
Loic

**Comment by tfranzel** [comment]
Hi @quertenmont,

> The open api type that comes out of this is 'array[string]', but that's incorrect, as the input is actually comma separated values the right type should be 'string'.

I believe we already do the right thing. Yes it is comma separated array, but the schema has 2 essential components. 1. the array schema and 2. the shape definition of the array `explode` and `style`.

We have `BaseInFilter` cases in the tests. They emit parameters like this:

```yaml
      - in: query
        name: in_categories
        schema:
          type: array
          items:
            type: string
            enum:
            - A
            - B
        description: Multiple values may be separated by commas.
        explode: false
        style: form
```

https://spec.openapis.org/oas/v3.0.3#style-examples

style | explode | empty | string | array | object
-- | -- | -- | -- | -- | --
form | false | color= | color=blue | color=blue,black,brown


According to spec I would say this is exactly what is needed here, right?


Note:
`map_serializer_field` does not exist on `OpenApiFilterExtension`, because it is specific to `OpenApiSerializerFieldExtension`. If you gonna write extensions please refer to the [interface documentation](https://github.com/tfranzel/drf-spectacular/blob/03d315ced245db71cef1e45fd05a082b7dedc7aa/drf_spectacular/extensions.py#L113). The readthedocs formatting makes this a bit harder to read, so code is prob easier.
