### ISSUE TITLE
ImageField or FileField is shown as string field in documentation

### ISSUE THREAD

**Issue by BinodKafle** [tfranzel/drf-spectacular#601]
**Describe the bug**
I have an `attachment` field which is defined as `models.FileField()` in my model. But in documentation, it is shown as a string input.

![image](https://user-images.githubusercontent.com/39294544/142380336-645e6e1c-8e92-465c-85d5-5a608d46f5cf.png)

**To Reproduce**
Define `models.ImageField()` or `models.FileField()` in your model. View schema type in swagger or redoc documentation

**Expected behavior**
Show as a file field instead of a string field

**Comment by ngnpope** [comment]
Please ensure that you have set `COMPONENT_SPLIT_REQUEST` to `True` in your settings.

This is already highlighted in the FAQ:

https://drf-spectacular.readthedocs.io/en/latest/faq.html#filefield-imagefield-is-not-handled-properly-in-the-schema

**Comment by tfranzel** [comment]
Hey @BinodKafle.

as @ngnpope pointed out, this is the expected behavior. The FAQ entry explains why that is in detail. This particular field is a multi-part/form encoded binary blob when inbound and a URL when outbound. OpenAPI does not provide a way to express this in a single component. `COMPONENT_SPLIT_REQUEST` takes care of this duality and other related issues.

**Comment by edmundsj** [comment]
Setting `COMPONENT_SPLIT_REQUEST = True` in my `settings.py` doesn't appear to do anything. The schema remains unchanged, and the attachment (in my case called "image") is just a string. Is anything other than setting that needs to be changed for this to be set appropriately? And what should I be expecting the schema to look like? 
```
    BaseImage:
      type: object
      properties:
        id:  
          type: integer
          readOnly: true 
        image:
          type: string
          format: uri
          nullable: true 
      required:
      - id 

```
The relevant model, serializer, and view:
```
# model
class BaseImage(models.Model):
    image = models.ImageField(null=True, upload_to='images')

# serializer
class BaseImageSerializer(ModelSerializer):
    class Meta:
        model = BaseImage
        fields = '__all__'

# view
class BaseImageViewSet(ModelViewSet):
    permission_classes = [IsAuthenticated, IsAuthenticatedOrReadOnly]
    serializer_class = BaseImageSerializer
 
```

**Comment by tfranzel** [comment]
@edmundsj that looks like the setting is not properly set. The settings are not plain in `settings.py`, they are nested in a dict, just as the readme says:

```python
SPECTACULAR_SETTINGS = {
    "COMPONENT_SPLIT_REQUEST": True,
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_SETTINGS": """{
        deepLinking: true,
        displayOperationId: true,
        persistAuthorization: true,
    }""",
    "VERSION": "0.0.1",
    "TITLE": "Your API",
    "DESCRIPTION": "Your API description",
}
```

**Comment by edmundsj** [comment]
Ah. Yup, that was the issue. Now the `BaseImage` is split into two refs: `BaseImage` and `BaseImageRequest`, with the latter looking like this:
```
    BaseImageRequest:
      type: object
      properties:
        image:
          type: string
          format: binary
          nullable: true
```
