### ISSUE TITLE
Redundant description on arrays

### ISSUE THREAD

**Issue by jayvdb** [tfranzel/drf-spectacular#61]
```yaml
    InlineConcreteBundle:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        triggering_product:
          type: integer
          description: Which product should trigger this bundle?
        suggested_products:
          type: array
          items:
            type: integer
            description: Which product(s) should this bundle suggest when triggered?
          description: Which product(s) should this bundle suggest when triggered?
      required:
      - id
      - suggested_products
      - triggering_product
```
