### ISSUE TITLE
Enhancement request: Persist the mappings

### ISSUE THREAD

**Issue by jayvdb** [tfranzel/drf-spectacular#65]
The mapping of endpoint to serializer/model/whatever is incredibly useful information which can be used for other introspection type tools.  It would be useful even if it was only created/updated when explicitly requested, such as a flag for the management command.

Immediate uses within drf-spectacular abound, but the most obvious and easy is to compare with reruns to detect changes in the mappings, and notify the invoker as mapping changes likely indicates the cause of some unexpected/beneficial change in generated API document.

Another use would be to augment [admindocs views](https://docs.djangoproject.com/en/3.0/ref/contrib/admin/admindocs/#view-reference) to provide a more detailed explanation of the data from that view.  It might even be possible to inject docstrings where they are missing in the format needed by admindocs so it can perform its duty better.

The longer term concept which made me think of this is to create an API edition of https://github.com/meshy/django-schema-graph , which visually shows the openapi entities interlinked.

It would also be possible to use this data in generation without tackling the complexity of round-tripping.  It would be wonderful to be able to create new mappings in the Django admin (i.e. a generated vs manual flag on the mapping data), which would allow manually mapping an APIView like djstripe's Subscription API to the appropriate serializer/model (c.f. https://github.com/tfranzel/drf-spectacular/pull/64).

**Comment by tfranzel** [comment]
that sounds very interesting. happy for any suggestions. i'm afraid i lack the time for this.

**Comment by jayvdb** [comment]
@tfranzel , what about as a first step, a comment is emitted into the YAML when settings.DEBUG is enabled, or a new specific flag.  e.g. the views and serializers

```yaml
paths:
  /oscarapi/checkout{format}:  # oscarapi.views.checkout.CheckoutView
    post:
      operationId: oscarapi_checkout{format}_create
      description"

components:
  schemas:
    Checkout:  # oscarapi.serializers.CheckoutSerializer
      type: object
      properties:

```
