### ISSUE TITLE
Django `FloatField` is incorrectly labeled as `float` (32-bit) OpenAPI format rather than `double` (64-bit)

### ISSUE THREAD

**Issue by johnthagen** [tfranzel/drf-spectacular#674]
Consider a Django model:

```py
class MyModel(Model):
    value = models.FloatField(null=True, blank=True)
```

From the [Django docs](https://docs.djangoproject.com/en/4.0/ref/models/fields/#floatfield)

> A floating-point number represented in Python by a `float` instance.

`float`'s in Python are effectively always 64-bit `double` precision floats (it may be possible on some bespoke embedded platforms like MicroPython they are something else, but those are out of scope for Django usage).

But `drf-spectacular`, generates a schema for this `FloatField` of:

```yaml
        value:
          type: number
          format: float
          nullable: true
```

According to the [OpenAPI 3 spec](https://swagger.io/docs/specification/data-models/data-types/), the correct format for this should be:

```yaml
        value:
          type: number
          format: double
          nullable: true
```

It's likely many users have not hit this because some common client languages (e.g. Python and JavaScript/TypeScript) only have one `float`/`number` type so this would not have an impact on the generated client code.

However, a language such as C# _does_ have two different floating point types, `float` and `double`. OpenAPI Generator using the `csharp-netcore` generator parses the `drf-spectacular` schema and uses 32-bit C# `float` instead of 64-bit `double`. This means that the client will lose precision that otherwise is stored in Django.

Example C# output:

```cs
        [DataMember(Name = "value", EmitDefaultValue = true)]
        public float? Value { get; set; }
```

Expected output:

```cs
        [DataMember(Name = "value", EmitDefaultValue = true)]
        public double? Value { get; set; }
```
