### ISSUE TITLE
`OpenApiParameter` with Python `float` type is incorrectly labeled as `float` (32-bit) OpenAPI format rather than `double` (64-bit)

### ISSUE THREAD

**Issue by johnthagen** [tfranzel/drf-spectacular#687]
**Describe the bug**
`OpenApiParameter` with the native Python `float` type is formatted as a 32-bit `float` rather than 64-bit `double`.

Related to #674

**To Reproduce**

Use `drf-spectacular` 0.22.0.

```py
input_param = OpenApiParameter(
    name="input",
    description="Description",
    type=float,
    default=1.0,
)


class MyViewSet(RetrieveModelMixin, GenericViewSet):
    @extend_schema(parameters=[input_param])
    def retrieve(self, request: Request, *args: Any, **kwargs: str) -> Response:
        ...
```

The resulting schema:

```yaml
        schema:
          type: number
          format: float
          default: 1.0
```

**Expected behavior**

Expected schema

```yaml
        schema:
          type: number
          format: double
          default: 1.0
```
