### ISSUE TITLE
Enum with a different names

### ISSUE THREAD

**Issue by tfranzel** [tfranzel/drf-spectacular#70]
Actually, one more note about the EvidenceRelationship schema. I have further updated the serializer to return two different relationships in a response:
```python
    @extend_schema_field(serializers.ChoiceField(choices=EvidenceRelationship.choices))
    def get_expert_consensus_relationship(self, obj: Evidence) -> EvidenceRelationship:
        return self.get_consensus(obj, expert=True)

    @extend_schema_field(serializers.ChoiceField(choices=EvidenceRelationship.choices))
    def get_community_consensus_relationship(self, obj: Evidence) -> EvidenceRelationship:
        return self.get_consensus(obj, expert=False)
```

This does work, but it's generating two separate enum types in the spec:

```yaml
    ExpertConsensusRelationshipEnum:
      enum:
      - PROVES
      - SUPPORTS
      - UNRELATED
      - INCONCLUSIVE
      - DISPUTES
      - DISPROVES
      - SPLIT
      type: string
    CommunityConsensusRelationshipEnum:
      enum:
      - PROVES
      - SUPPORTS
      - UNRELATED
      - INCONCLUSIVE
      - DISPUTES
      - DISPROVES
      - SPLIT
      type: string
```

Is there any way to tell drf-spectacular that these are the same enum?

_Originally posted by @KunstDerFuge in https://github.com/tfranzel/drf-spectacular/issues/68#issuecomment-633932856_
