### ISSUE TITLE
How to define a security scheme involving 2 cookie parameters?

### ISSUE THREAD

**Issue by bluelight773** [tfranzel/drf-spectacular#722]
I'd like the `SessionScheme` corresponding to `rest_framework.authentication.SessionAuthentication` to use 2 cookie parameters instead of one.

What I've tried but doesn't work (the security scheme isn't even shown as an option when I click Authorize in SwaggerUI). If I only include one cookie parameter, then this works, but I need it to work for 2 cookie parameters.

```py
from drf_spectacular.authentication import SessionScheme


def get_security_definition(self, auto_schema):
    return [
        {
            "type": "apiKey",
            "in": "cookie",
            "name": "cookie_param1",
        },
        {
            "type": "apiKey",
            "in": "cookie",
            "name": "cookie_param2",
        },
    ]


SessionScheme.get_security_definition = get_security_definition
SessionScheme.name = "TwoCookieParamAuth"
```

https://github.com/swagger-api/swagger-ui/issues/4218#issuecomment-656688147 suggests I may be able to define the desired security scheme with something along the following lines. However, I'm not sure how to define such a scheme with drf-spectacular.
```yaml
get:
    summary: Test endpoint
    parameters:
        - name: authCookie
          schema:
            type: object
            properties:
              cookie1:
                type: string
              cookie2:
                type: string                  
          in: cookie
          explode: true
          style: matrix
```

Any ideas on how to define a 2-cookie-parameter security scheme with drf-spectacular?

Thanks!
