### ISSUE TITLE
[django-filter] `@extend_schema_field` on a `[Multiple]ChoiceFilter` cannot override enum autodetection

### ISSUE THREAD

**Issue by diesieben07** [tfranzel/drf-spectacular#735]
**Describe the bug**
`@extend_schema_field` can be used to specify a custom schema for a django-filter filter. This however cannot override the `enum` part of the final schema, because `DjangoFilterExtension` unconditionally overwrites this part of the schema in case it finds explicit choices mentioned on the `ChoiceField`.

**To Reproduce**
```python
PROJECT_TYPE_CHOICES = (
    ('finished', 'finished',),
    ('unfinished', 'unfinished',),
)


class ProjectFilterSet(filters.FilterSet):
    type = extend_schema_field(
        {
            'type': 'string',
        }
    )(filters.ChoiceFilter(choices=PROJECT_TYPE_CHOICES))
```

Using this FilterSet will yield a schema as follows:
```yaml
/projects/:
  get:
    operationId: projects_list
    parameters:
    - in: query
      name: type
      schema:
        type: string
        enum:
        - finished
        - unfinished
```
Note the generated `enum`, which cannot be overridden _at all_, even when setting `enum` to `None` explicitly in `extend_schema_field`.

**Expected behavior**
I will grant that this is very much an edge-case, but I would still argue that `extend_schema_field` should disable _any_ autodetection and simply output the schema as given without any further processing.

As such I would have expected the following schema in the example above:
```yaml
/projects/:
  get:
    operationId: projects_list
    parameters:
    - in: query
      name: type
      schema:
        type: string
```
