### ISSUE TITLE
How to define examples in extend_schema when response is list of serializer

### ISSUE THREAD

**Issue by haminhcong** [tfranzel/drf-spectacular#788]
Hi! I've been using drf-spectacular for documenting my swagger API. 

I'm trying to define example response for an API return a List of Searializer. I tried to use `many=True` in response:

```python
EXAMPLE_RESPONSE_ARTIFACTS = OpenApiExample(
    name='EXAMPLE_RESPONSE_ARTIFACTS',
    status_codes=["200"],
    response_only=True,
    value=[
        {
            "name": "ar-1",
            "id": "121",
        },
        {
            "name": "ar-2",
            "id": "122",
        },
        {
            "name": "ar-3",
            "id": "123",
        },

    ]
)

@extend_schema(parameters=[PARAM_PROJECT_ID, PARAM_IMAGE_NAME, PARAM_REFERENCE],
               responses={200: OpenApiResponse(
                   description='Request successful.',
                   response=ArtifactSerializer(many=True),
                   examples=[EXAMPLE_RESPONSE_ARTIFACTS]
               )})

```

But when swagger.yaml file rendered, the example response has two layers of brackets:

![Screenshot 2022-08-20 at 12-09-50 CMP Backend API](https://user-images.githubusercontent.com/16532870/185729974-c3daad4d-4079-4fb8-8295-823589b4a15c.png)

```yaml
              examples:
                EXAMPLE_RESPONSE_ARTIFACTS:
                  value:
                  - - name: ar-1
                      id: '121'
                    - name: ar-2
                      id: '122'
                    - name: ar-3
                      id: '123'
```

So in this usage scenario, what is the correct way for me to define example for API Reponse?
