### ISSUE TITLE
How do we set the API URL for the schema?

### ISSUE THREAD

**Issue by Routhinator** [tfranzel/drf-spectacular#855]
With the DRF stock OpenAPI generator, you set the URL of the API when you add the route to urls.py:

```python
schema_view = get_schema_view(
    title='Server Monitoring API',
    url='https://api.staging.mydomain.com',
    patterns=schema_url_patterns,
)
```

However I do not see any settings relating to this aside from `SCHEMA_PATH_PREFIX` and `SERVERS`.

I have set those like:

```python
    'SERVERS': [
        {
            'url': 'https://api.staging.mydomain.com',
        },
    ],
    'SCHEMA_PATH_PREFIX': 'https://api.staging.mydomain.com',
```

However the schema is being generated with examples that are all using `http://api.example.com` 

```yaml
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
```

DRF generates these urls dynamically based on the request URL, while also allowing the URL to be set for the schema generation - however I do not see any such way to set the URL for drf-spectacular. 

I've been digging through the docs to find any mention of how to set this but I'm missing something - or some form of automagic url discovery is broken in my setup and I need a hand finding it.
