### ISSUE TITLE
application/json field should not be generated with schemas that have binary encoding

### ISSUE THREAD

**Issue by edmundsj** [tfranzel/drf-spectacular#871]
**Describe the bug**
drf-spectacular generates `application/json` content type even when this content type does not support the underlying models. This causes an issue with downstream API client generation and prevents upload/download of files, such as images, using that API client. See [this issue](https://github.com/openapi-generators/openapi-python-client/issues/453)

**To Reproduce**
Include a model / serializer / view combination that has a `FileField` or `ImageField`. My configuration (excluding imports and `urls.py`):

`models.py`
```
class DOImage(models.Model):
    file = models.ImageField()
    uploaded_at = models.DateTimeField(auto_now_add=True)
```

`serializers.py`
```
class DOImageSerializer(ModelSerializer):
    class Meta:
        model = DOImage
        fields = '__all__'
```

`views.py`
```
class DOImageViewSet(ModelViewSet):
    serializer_class = DOImageSerializer
    queryset = DOImage.objects.all()
```

The generated schema contains the following region for the `post` method of my specified endpoint:
```

   post:
      operationId: community_images_create
      tags:
      - community
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DOImageRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/DOImageRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/DOImageRequest'
```
And the referred to component schema:
```
    DOImageRequest:                                                                                 
      type: object
      properties:
        file:
          type: string
          format: binary
      required:
      - file
```

**Expected behavior**
`application/json` is not a valid way of encoding binary files. This should be excluded from the generated `content-types` automatically by `drf-spectacular` when any of the component schemas have a property with binary format. The only generated content should be a `multipart/form-data` content type.
