### ISSUE TITLE
Extend ModelSerializer autogenerated fields

### ISSUE THREAD

**Issue by chgad** [tfranzel/drf-spectacular#873]
**Describe the bug**

It is not possible to extend fields which were autogenerated by a `ModelSerializer`. 
Defining a custom serializerfield and extending it results in loosing the Info provided by the model field.

**To Reproduce**

Suppose the following model:

``` 
class Word(SolidBaseProfile):
    name = models.CharField(max_length=200, verbose_name=_("Titel"))

    graphic = models.TextField(
        max_length=500,
        null=True,
        blank=True,
        verbose_name=_("Graphie"),
    )
```

Furthermore let's say we introduce a new "type" of string called "mdstring" to let our forntend know, that it has to render the contents as markdown formatted text.

If you define the following field + serializer

``` 
@extend_schema_field({"type": "mdstring"})
class MDStringField(serializers.CharField):
    pass

class WordSerializer(serializers.ModelSerializer):
    graphic = MDStringField()

    class Meta:
        model = Word
        fields = "__all__"
```

The resulting Schema becomes:

``` 
    Word:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        graphic:
          type: mdstring
        name:
          type: string
          title: Titel
          maxLength: 200
```

**Expected behavior**

Since i'm not sure if this is a pure `drf-spectacular` Problem i'm just stating what i would like to achive.

The schema i would like to see is:

``` 
    Word:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        graphic:
          type: mdstring
          nullable: true
          title: Graphie
          maxLength: 500
        name:
          type: string
          title: Titel
          maxLength: 200
```
