### ISSUE TITLE
Possibility to rename a PATH param, and have the PATH updated accordingly 

### ISSUE THREAD

**Issue by mouadennasri** [tfranzel/drf-spectacular#927]
**Issue**
I'm trying to rename a specific PATH parameter, but I can't find any override mechanism to do so! 

I have the following ViewSet:

views.py
```python
@extend_schema(
    parameters=[],
    request=UpdateAccountSerializer,
    responses=BaseSerializer,
    description="Account Update View",
    tags=["User Account"],
)
class AccountUpdateViewSet(
    mixins.UpdateModelMixin,
    viewsets.GenericViewSet,
):
    queryset = Account.objects.filter().prefetch_related("memberships__company")
    serializer_class = UpdateAccountSerializer
    permission_classes = (permissions.AllowAny,)

    def partial_update(self, request, *args, **kwargs):
        instance = self.get_object()
        serializer = self.serializer_class(instance, data=request.data, partial=True)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(AccountDetailSerializer(instance).data)
```
urls.py
```python
router.register(r"accounts/", AccountUpdateViewSet)
```

this will result in the following open-api schema:
```yaml
/accounts/{id}:
    patch:
      operationId: accounts_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
        description: A unique value identifying this account.
        required: true
```

So I'm looking for a way to adjust the ViewSet so it can override the default `{id}` and use `{account_id}` instead
Without changing the `lookup_field` or the `model` primary key!

Maybe having a property in the OpenApiParameter as `alias` will help:

```python
OpenApiParameter(
    name="account_id",
    location=OpenApiParameter.PATH,
    type=str,
    description='A unique value identifying this account.',
    required=True,
    alias="id"
),
```
For example this will override the default `{id}` PATH param and use `{account_id}` instead!
and you will get:

```yaml
/accounts/{account_id}:
    patch:
      operationId: accounts_partial_update
      parameters:
      - in: path
        name: account_id
        schema:
          type: string
        description: A unique value identifying this account.
        required: true
```
Maybe I'm missing something let me know if that's the case and thank you in advance!
