### ISSUE TITLE
help_text defined on model is overridden with empty help_text from serialiser level

### ISSUE THREAD

**Issue by diego351** [tfranzel/drf-spectacular#942]
**Describe the bug**
Valid help_text defined on model fields are overridden with empty help_text from serialiser level

**To Reproduce**

```
class Brand(models.Model):
    image = models.ImageField(blank=True, upload_to="images", help_text='Wanted help_text')

class BrandSerializer(ModelSerializer):
    from drf_extra_fields.fields import Base64ImageField
    image = Base64ImageField(required=False)
   
    class Meta:
        model = Brand
        fields = ('id', 'image')

class BrandListView(ListAPIView):
    model = Brand
    serializer_class = BrandSerializer
    pagination_class = LimitOffsetPagination
    queryset = model.objects.all()

```
produces:

```
 Brand:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        image:
          type: string
          format: uri # <- no description
      required:
      - id
```
  

**Expected behavior**

help_text on model level shouldn't be overridden with empty help_text on serialiser level. These help_text will makes sense for most of the cases. They should only be overridden if explicitly defined on serialiser level.  Other examples of unwanted overriden help_text: https://github.com/tfranzel/drf-spectacular/issues/941#issuecomment-1435975449

Please don't close the issue right away, let the people have their vote.
