### ISSUE TITLE
"title" keyword missing when it is equal to verbose_name

### ISSUE THREAD

**Issue by chgad** [tfranzel/drf-spectacular#948]
**Describe the bug**

Defining a django model field with a verbose_name that does only differ in capitalization from the fieldname will result in missing the `"title"` keyword in the schema.

**To Reproduce**
Consider the following model/serializer:

``` python
class TestModel(models.Model):
    name = models.CharField(max_length=200, verbose_name=_("Name"))

class TestModelSerializer(serializer.ModelSerializer):

        class Meta:
            model = TestModel
            fields = "__all__"

```

The schema generated is:

```yaml
    TestModel:
      type: object
        name:
          type: string
          maxLength: 200
```

**Expected behavior**

I'd expect the title to be present wether the `verbose_name` is equal to the field name or not.

```yaml
    TestModel:
      type: object
        name:
          type: string
          title: "Name"
          maxLength: 200
```

INFO: 

I searched the OpenAPI Specification, the [JSON Schema validation](https://datatracker.ietf.org/doc/html/draft-wright-json-schema-validation-00) and the [JSON Schema](https://datatracker.ietf.org/doc/html/draft-wright-json-schema-00) mentioned in it.
The result: This behavior is not mentioned anywhere.

Was it intended by design or is it an actual bug?
