### ISSUE TITLE
Generating docstring from rest_framework serializers on Drf 26.0

### ISSUE THREAD

**Issue by nathanmrtns** [tfranzel/drf-spectacular#955]
**Describe the bug**
The generator is adding docstrings coming from thirdparty lib if we use a field named "value" and instead of a Decimal field we put a method field.

**To Reproduce**
```python
from rest_framework import serializers

class MySerializer(serializers.ModelSerializer):
    value = serializers.SerializerMethodField()

    class Meta:
        model = MyModel
        fields = ("value")

    get_value(self, obj) -> Decimal:
         return obj.get_value()
```

implementation in rest_framework/fields.py
```python
    def get_value(self, dictionary):
        """
        Given the *incoming* primitive data, return the value for this field
        that should be validated and transformed to a native value.
        """
```

The output in the schema is this, were the description is the docstring coming from the serializer methods get_value implementation:

```yml
value:
  type: number
  format: double
  description: |-
    Given the *incoming* primitive data, return the value for this field
    that should be validated and transformed to a native value.
```

Note: If I add a docstring in the serializer method, it will generate correctly.

**Expected behavior**
It sholdn't generate the description if the serializer method doesn't have a docstring.
