### ISSUE TITLE
PositiveIntegerField schema depends on the DB backend

### ISSUE THREAD

**Issue by zhiltsov-max** [tfranzel/drf-spectacular#962]
**Describe the bug**
Hi, it seems that the schema generated may depend on the DB backend used. Given the following 
declaration:

```python
from django.db import models
from rest_framework import serializers

class MyModel(models.Model):
    pos_int_field = models.PositiveIntegerField(null=True)

class MyModelSerializer(serializers.ModelSerializer):
    class Meta:
        model = models.MyModel
        fields = ('pos_int_field', )
```

And 2 DB backends for development (Sqlite3) and production (Postgres):

```python
# development
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        ...
    },
}

# production
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        ...
    }
}
```

We have 2 different schemes generated:

```yaml
# with sqlite3
    MyModelRequest:
      type: object
      properties:
        pos_int_field:
          type: integer
          nullable: true

# with postgres
    MyModelRequest:
      type: object
      properties:
        pos_int_field:
          type: integer
          maximum: 2147483647 # extra field
          minimum: 0 # extra field
          nullable: true
```

**How to reproduce**

Out environment is:
```
Django==3.2.18
djangorestframework==3.12.4
drf-spectacular==0.22.1
```

**Expected behavior**
Probably, the API schema fields should not depend on the server DB backend used, and the schema generated should be the same in both cases.
