### ISSUE TITLE
Support for simple parameter examples

### ISSUE THREAD

**Issue by fgreinacher** [tfranzel/drf-spectacular#981]
Is there a way to declare simple, unnamed examples for parameters?

For example to get this from the [OpenAPI docs](https://swagger.io/docs/specification/adding-examples/):

```yml
parameters:
  - in: query
    name: status
    schema:
      type: string
      enum: [approved, pending, closed, new]
      example: approved
```

I have tried the `examples` parameter for `OpenApiParameter`, but that can only be used for named examples, e.g. like this:

```yml
parameters:
  - in: query
    name: status
    schema:
      type: string
      enum: [approved, pending, closed, new]
      examples: 
        zero:
          value: approved
```
