### ISSUE TITLE
`OpenApiParameter` `minimum` and `maximum` parameter

### ISSUE THREAD

**Issue by johnthagen** [tfranzel/drf-spectacular#986]
Would it be within scope to allow defining an `OpenApiParameter` like this:

```py
max_size_param = OpenApiParameter(
    name="max_size",
    type=int,
    minimum=0,
    maximum=1000,
)
```

This would map to OpenAPI 3's `minimum` and `maximum` properties and seem like they would fit in well with the existing `default` option.

- https://swagger.io/docs/specification/describing-parameters/

```yaml
    limitParam:
      in: query
      name: limit
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 50
        default: 20
```

Related to

- #384
